echo "tput debugging..."
echo "$(tput dim)$(tput setaf 2)green dim$(tput sgr0)"
echo "$(tput setaf 2)green$(tput sgr0)"
echo "$(tput setaf 10)green bright$(tput sgr0)"
echo "$(tput bold)$(tput setaf 2)green bold$(tput sgr0)"
echo "$(tput smso)$(tput setaf 2)green standout$(tput sgr0)"
echo "$(tput rev)$(tput setaf 2)green rev$(tput sgr0)"
echo "$(tput blink)$(tput setaf 2)green blink$(tput sgr0)"
echo "$(tput smul)$(tput setaf 2)green underlined$(tput sgr0)"
