apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: diva-trading-app-db
  namespace: default
spec:
  teamId: diva
  volume:
    size: 1Gi
  numberOfInstances: 4
  users: {}
  databases: {}
  preparedDatabases: {}
  postgresql:
    version: "13"
