apiVersion: v1
kind: Pod
metadata:
  name: {{app_name}}-test
spec:
  containers:
    - name: container
      image: postgres:13.4
      stdin: true
      command: ['bash']
      volumeMounts:
        - name: volume-sqls
          mountPath: /app/sqls
        - name: volume-init
          mountPath: /app/init
      env:
        - name: DB_HOST
          value: {{app_name}}-db
        - name: SQL_ROOT
          value: /app/sqls
        - name: USER
          valueFrom:
            secretKeyRef:
              name: postgres.{{app_name}}-db.credentials.postgresql.acid.zalan.do
              key: username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres.{{app_name}}-db.credentials.postgresql.acid.zalan.do
              key: password
  volumes:
    - name: volume-sqls
      configMap:
        name: {{app_name}}-cm-sqls
    - name: volume-init
      configMap:
        name: {{app_name}}-cm-init-db
